remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

theme: jekyll-theme-modernist
title: Nikye Nixon's Game Portfolio
description: Bookmark this to keep an eye on my project updates!

header_pages:
- index.md
- games.md
- about.md
