title: Nikye Nixon's Game Portfolio
email: nixonn@umich.edu
description: Bookmark this to keep an eye on my project updates!

theme: jekyll-theme-minimal

header_pages:
  - index.md
  - games.md
  - about.md
